const { USER_CATEGORIES } = require("./userConstants");

const PERMISSION_TYPES = {
    ANY: 'any',
    SUPER_ADMIN: USER_CATEGORIES.SUPER_ADMIN,
    ADMINISTRATOR: USER_CATEGORIES.ADMIN,
    DRIVER: USER_CATEGORIES.DRIVER,
    CUSTOMER: USER_CATEGORIES.CUSTOMER,
    RESTAURANT: USER_CATEGORIES.RESTAURANT,
    REGISTERED: USER_CATEGORIES.REGISTERD,
    OWNER: 'owner'
};

module.exports = {PERMISSION_TYPES};
