version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - mealwhirl-network

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
    networks:
      - mealwhirl-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5001:5001"
    environment:
      - APP_HOST=0.0.0.0
      - PORT=5001
      - ENV=dev
      - KAFKA_BROKER=kafka:9092
      - MONGO_URI=mongodb+srv://randini:Randini@cluster0.ojx49ry.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - kafka
      - api-gateway
    networks:
      - mealwhirl-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "5002:5002"
    environment:
      - APP_HOST=0.0.0.0
      - PORT=5002
      - ENV=dev
      - KAFKA_BROKER=kafka:9092
      - MONGO_URI=mongodb+srv://randini:Randini@cluster0.ojx49ry.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - kafka
      - api-gateway
    networks:
      - mealwhirl-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "5000:5000"
    environment:
      - APP_HOST=0.0.0.0
      - PORT=5000
      - ENV=dev
      - KAFKA_BROKER=kafka:9092
    networks:
      - mealwhirl-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./api-gateway/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-gateway
      - user-service
    networks:
      - mealwhirl-network

networks:
  mealwhirl-network:
    name: mealwhirl-network
    driver: bridge