apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: mealwhirl-server/user-service
          image: mealwhirl-server-user-service:latest
          ports:
            - containerPort: 5001
          env:
            - name: NODE_ENV
              value: "test"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: user-service-secrets
                  key: db_url
            - name: KAFKA_BROKER
              value: "kafka-service:9092"
            - name: PORT
              value: "5001"
            - name: APP_HOST
              value: "0.0.0.0"
            - name: ENV
              value: "test"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: user-service-secrets
                  key: db_url
            - name: TOKEN_SECRET
              valueFrom:
                  secretKeyRef:
                    name: user-service-secrets
                    key: jwt_secret
              
